### ISSUE TITLE
lvgl_micropython

### ISSUE THREAD

**Issue by Shynka** [straga/micropython_lcd#1]
Which command did you use to start make.py

**Comment by straga** [comment]
I build from Micropython as USER_C_MODULES

But you can try:

## 1. 
 build for any board, after that copy file to board over (webrepl, mpremote or ... .)
`python3 make.py esp32 BOARD=ESP32_GENERIC_S3 BOARD_VARIANT=SPIRAM_OCT DISPLAY=st7796 INDEV=gt911`

## 2. 
copy file from repo to lvgl_micropython and build with DISPLAY=axs15231b INDEV=axs15231b_touch`

## 3. 
I build from Micropython as USER_C_MODULES, but need first 

- have esp-idf env 
- You can build Micropython from scratch with your own board
- Need create some board with some other stuff
    ### sdkconfig.base add:
        CONFIG_FREERTOS_INTERRUPT_BACKTRACE=n
        CONFIG_FREERTOS_IDLE_TASK_STACKSIZE=4096
    ### Configure partition and own manifest

    ### submodules
        cd to dir lvgl_micropython:
            git submodule update --init lib/pycparser
            git submodule update --init lib/lvgl

    ### in the build directory create 
        lvgl_micropython/build -> crate file lvgl_header.h
    
        #include "{Absolute path from root}/lvgl_micropython/lib/lvgl/lvgl.h"
        #include "{Absolute path from root}/lvgl_micropython/lib/lvgl/src/lvgl_private.h"

## Alter you can build:
      `make -j 9 SECOND_BUILD=0 LV_PORT=esp32s3 LV_CFLAGS="-DLV_KCONFIG_IGNORE=1" BOARD=STRAGA_S3_SPIRAM_LCD USER_C_MODULES=~/opt/upy/cmodules/lvgl/lvgl_micropython/ext_mod/micropython.cmake`

**Comment by straga** [comment]
Add firmware:
https://github.com/straga/micropython_lcd/tree/master/device

**Comment by Shynka** [comment]
Thanks so much its working as you previewed
